apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-bundle
  namespace: default
data:
  policy.rego: "package policy\n\nimport future.keywords.if\n\ndefault allow := false\n\nis_post
    if {\n    input.method == \"POST\"\n}\n\nis_users_endpoint if {\n    input.path
    == \"/api/users\"\n}\n\nis_admin if {\n    token.role.type == \"admin\"\n}\n\nis_api_call
    if {\n    startswith(input.path, \"/api/\")\n}\n\n# allow rules\nallow if {\n
    \   input.method == \"GET\"\n    not is_api_call\n}\n\nallow if {\n\tinput.method
    == \"POST\"\n\tis_users_endpoint\n\tis_admin\n}\n\nallow if {\n\tis_users_endpoint\n\ttoken\n
    \   input.method == \"GET\"\n}\n# end allow rules\n\n\ntoken := payload if {\n\t#
    Verify the signature on the Bearer token.\n\tio.jwt.verify_hs256(bearer_token,
    \"SECRET\")\n\t[_, payload, _] := io.jwt.decode(bearer_token)\n}\n\nbearer_token
    := t if {\n\t# Bearer tokens are contained inside of the HTTP Authorization header.
    This rule\n\t# parses the header and extracts the Bearer token value. If no Bearer
    token is\n\t# provided, the `bearer_token` value is undefined.\n\tv := input.authorization\n\tstartswith(v,
    \"Bearer \")\n\tt := substring(v, count(\"Bearer \"), -1)\n}\n"
  test_policy.rego: |
    package tests

    import future.keywords
    import data.policy.allow

    admin_token := "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3RyaW5nIiwiZW1haWwiOiJzdHJpbmciLCJyb2xlIjp7InR5cGUiOiJhZG1pbiJ9fQ.dqJ25D7XOYmdNNdn46Qa89EAIq5nQshVZwkGAYo1x1Q"
    regular_token := "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9obiBkb2UiLCJlbWFpbCI6InN0cmluZ0BtYWlsLmRvdCIsInJvbGUiOnsidHlwZSI6InJlZ3VsYXIifX0.BOwjeyGLfo-_wVqVObyiZuLI-XcTbpdzzdDWdhNP_1g"
    invalid_admin_token := "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3RyaW5nIiwiZW1haWwiOiJzdHJpbmciLCJyb2xlIjp7InR5cGUiOiJhZG1pbiJ9fQ.dqJ25D7XOYmdNNdn46Qa89EAIq5nQshVZwkGAYo1x1Z"

    test_allow_get_to_root_endpoint_no_auth if {
        allow with input as {
            "method": "GET",
            "path": "/"
        }
    }


    test_get_request_authenticated_regular_user if {
        allow with input as {
            "method": "GET",
            "authorization": regular_token,
            "path": "/api/users"
        }
    }

    test_get_request_authenticated_admin_user if {
        allow with input as {
            "method": "GET",
            "authorization": admin_token,
            "path": "/api/users"
        }
    }


    test_invalid_token_request_authenticated if {
        not allow with input as {
            "method": "GET",
            "authorization": invalid_admin_token,
            "path": "/api/users"
        }
    }

    test_unauthenticated_get if {
        not allow with input as {
            "method": "GET",
            "path": "/api/users"
        }
    }


    test_unauthenticated_post if {
        not allow with input as {
            "method": "GET",
            "path": "/api/users"
        }
    }

    test_post_request_admin if {
        allow with input as {
            "authorization": admin_token,
            "method": "POST",
            "path": "/api/users"
        }
    }

    test_post_request_non_admin if {
        not allow with input as {
            "authorization": regular_token,
            "method": "POST",
            "path": "/api/users"
        }
    }

    test_post_request_non_admin if {
        not allow with input as {
            "authorization": invalid_admin_token,
            "method": "POST",
            "path": "/api/users"
        }
    }
