apiVersion: v1
kind: Service
metadata:
  name: users-app-service
  labels:
    app: users-app
spec:
  selector:
    app: users-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: NodePort
